# Assignment 2

In this assigment, we will work with the *Forest Fire* data set. Please download the data from the [UCI Machine Learning Repository](https://archive.ics.uci.edu/dataset/162/forest+fires). Extract the data files into the subdirectory: `../data/fires/` (relative to `./05_src/`).

## Objective

+ The model objective is to predict the area affected by forest fires given the features set. 
+ The objective of this exercise is to assess your ability to construct and evaluate model pipelines.
+ Please note: the instructions are not meant to be 100% prescriptive, but instead they are a set of minimum requirements. If you find predictive performance gains by applying additional steps, by all means show them. 

## Variable Description

From the description file contained in the archive (`forestfires.names`), we obtain the following variable descriptions:

1. X - x-axis spatial coordinate within the Montesinho park map: 1 to 9
2. Y - y-axis spatial coordinate within the Montesinho park map: 2 to 9
3. month - month of the year: "jan" to "dec" 
4. day - day of the week: "mon" to "sun"
5. FFMC - FFMC index from the FWI system: 18.7 to 96.20
6. DMC - DMC index from the FWI system: 1.1 to 291.3 
7. DC - DC index from the FWI system: 7.9 to 860.6 
8. ISI - ISI index from the FWI system: 0.0 to 56.10
9. temp - temperature in Celsius degrees: 2.2 to 33.30
10. RH - relative humidity in %: 15.0 to 100
11. wind - wind speed in km/h: 0.40 to 9.40 
12. rain - outside rain in mm/m2 : 0.0 to 6.4 
13. area - the burned area of the forest (in ha): 0.00 to 1090.84 









### Specific Tasks

+ Construct four model pipelines, out of combinations of the following components:

    + Preprocessors:

        - A simple processor that only scales numeric variables and recodes categorical variables.
        - A transformation preprocessor that scales numeric variables and applies a non-linear transformation.
    
    + Regressor:

        - A baseline regressor, which could be a [K-nearest neighbours model]() or a linear model like [Lasso](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html) or [Ridge Regressors](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ridge_regression.html).
        - An advanced regressor of your choice (e.g., Bagging, Boosting, SVR, etc.). TIP: select a tree-based method such that it does not take too long to run SHAP further below. 

+ Evaluate tune and evaluate each of the four model pipelines. 

    - Select a [performance metric](https://scikit-learn.org/stable/modules/linear_model.html) out of the following options: explained variance, max error, root mean squared error (RMSE), mean absolute error (MAE), r-squared.
    - *TIPS*: 
    
        * Out of the suggested metrics above, [some are correlation metrics, but this is a prediction problem](https://www.tmwr.org/performance#performance). Choose wisely (and don't choose the incorrect options.) 

+ Select the best-performing model and explain its predictions.

    - Provide local explanations.
    - Obtain global explanations and recommend a variable selection strategy.

+ Export your model as a pickle file.


You can work on the Jupyter notebook, as this experiment is fairly short (no need to use sacred). 

# Load the data

Place the files in the ../../05_src/data/fires/ directory and load the appropriate file. 

In [52]:
# Load the libraries as required.
import pandas as pd
from sklearn.preprocessing import StandardScaler, PolynomialFeatures, OneHotEncoder, FunctionTransformer
import matplotlib.pyplot as plt
import numpy as np
import random
from sklearn.compose import ColumnTransformer, TransformedTargetRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate, train_test_split, KFold, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.metrics import root_mean_squared_error, r2_score

# from sklearn.tree import DecisionTreeClassifier
# from sklearn.metrics import accuracy_score, log_loss, cohen_kappa_score, f1_score

In [53]:
# Load data
columns = [
    'coord_x', 'coord_y', 'month', 'day', 'ffmc', 'dmc', 'dc', 'isi', 'temp', 'rh', 'wind', 'rain', 'area' 
]
fires_dt = (pd.read_csv('../../05_src/data/fires/forestfires.csv', header = 0, names = columns))
fires_dt.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   coord_x  517 non-null    int64  
 1   coord_y  517 non-null    int64  
 2   month    517 non-null    object 
 3   day      517 non-null    object 
 4   ffmc     517 non-null    float64
 5   dmc      517 non-null    float64
 6   dc       517 non-null    float64
 7   isi      517 non-null    float64
 8   temp     517 non-null    float64
 9   rh       517 non-null    int64  
 10  wind     517 non-null    float64
 11  rain     517 non-null    float64
 12  area     517 non-null    float64
dtypes: float64(8), int64(3), object(2)
memory usage: 52.6+ KB


# Get X and Y

Create the features data frame and target data.

In [54]:
# Create target data frame
df_area_burnt = fires_dt[['area']]
# Create the features data frame
fires_feat = fires_dt.drop(columns=['area'])

In [55]:
df_area_burnt.describe()

,area
count,517.000000
mean,12.847292
std,63.655818
min,0.000000
25%,0.000000
50%,0.520000
75%,6.570000
max,1090.840000


In [56]:
fires_feat.describe()

,coord_x,coord_y,ffmc,dmc,dc,isi,temp,rh,wind,rain
count,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000
mean,4.669246,4.299807,90.644681,110.872340,547.940039,9.021663,18.889168,44.288201,4.017602,0.021663
std,2.313778,1.229900,5.520111,64.046482,248.066192,4.559477,5.806625,16.317469,1.791653,0.295959
min,1.000000,2.000000,18.700000,1.100000,7.900000,0.000000,2.200000,15.000000,0.400000,0.000000
25%,3.000000,4.000000,90.200000,68.600000,437.700000,6.500000,15.500000,33.000000,2.700000,0.000000
50%,4.000000,4.000000,91.600000,108.300000,664.200000,8.400000,19.300000,42.000000,4.000000,0.000000
75%,7.000000,5.000000,92.900000,142.400000,713.900000,10.800000,22.800000,53.000000,4.900000,0.000000
max,9.000000,9.000000,96.200000,291.300000,860.600000,56.100000,33.300000,100.000000,9.400000,6.400000


Stratified Split Train/Test

In [57]:
# Setting a random seed for GridSearchCV and cross_validate later used, even though we finally found how to embed random_state inside those objects, I left it in case I will need it
random.seed(42)

# Assuming `fires_feat` is your feature set and `df_area_burnt` is your target
stratify_labels = (df_area_burnt == 0).astype(int)  # Convert target into binary labels

fires_feat_train, fires_feat_test, df_area_burnt_train, df_area_burnt_test = train_test_split(
    fires_feat, df_area_burnt, test_size=0.2, stratify=stratify_labels, random_state=42
)

print(f"Train target distribution: {df_area_burnt_train.value_counts(normalize=True)}")
print(f"Test target distribution: {df_area_burnt_test.value_counts(normalize=True)}")

# to shorten variable names
fires_feat = fires_feat_train.copy()
df_area_burnt = df_area_burnt_train.copy()
fires_dt = pd.concat([fires_feat,df_area_burnt], axis=1)

Train target distribution: area   
0.00       0.476998
1.94       0.007264
0.90       0.004843
9.27       0.004843
9.96       0.004843
             ...   
3.64       0.002421
3.78       0.002421
3.93       0.002421
3.94       0.002421
1090.84    0.002421
Name: proportion, Length: 201, dtype: float64
Test target distribution: area  
0.00      0.480769
23.41     0.009615
9.71      0.009615
10.02     0.009615
10.73     0.009615
10.93     0.009615
11.06     0.009615
11.16     0.009615
12.10     0.009615
16.33     0.009615
16.40     0.009615
17.85     0.009615
22.03     0.009615
24.23     0.009615
8.31      0.009615
24.77     0.009615
28.19     0.009615
34.36     0.009615
42.87     0.009615
46.70     0.009615
48.55     0.009615
49.37     0.009615
58.30     0.009615
61.13     0.009615
174.63    0.009615
212.88    0.009615
8.71      0.009615
7.73      0.009615
0.17      0.009615
2.75      0.009615
0.68      0.009615
0.95      0.009615
1.01      0.009615
1.26      0.009615
1.36      0.009615
1

Non-Stratified Split Train/Test. Disabled

In [58]:
# # Setting a random seed for GridSearchCV and cross_validate later used, even though we finally found how to embed random_state inside those objects
# random.seed(42)
# # Splitting Strategy: Create training and test datasets
# fires_feat_train, fires_feat_test, df_area_burnt_train, df_area_burnt_test = train_test_split(fires_feat, df_area_burnt, test_size=0.2, random_state=42)
# #print(fires_feat_train.shape, fires_feat_test.shape, df_area_burnt_train.shape, df_area_burnt_test.shape)
# # to shorten variable names
# fires_feat = fires_feat_train.copy()
# df_area_burnt = df_area_burnt_train.copy()
# fires_dt = pd.concat([fires_feat,df_area_burnt], axis=1)

# Preprocessing

Create two [Column Transformers](https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html), called preproc1 and preproc2, with the following guidelines:

- Numerical variables

    * (Preproc 1 and 2) Scaling: use a scaling method of your choice (Standard, Robust, Min-Max). 
    * Preproc 2 only: 
        
        + Choose a transformation for any of your input variables (or several of them). Evaluate if this transformation is convenient.
        + The choice of scaler is up to you.

- Categorical variables: 
    
    * (Preproc 1 and 2) Apply [one-hot encoding](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html) where appropriate.


+ The only difference between preproc1 and preproc2 is the non-linear transformation of the numerical variables.
    


### Preproc 1

Create preproc1 below.

+ Numeric: scaled variables, no other transforms.
+ Categorical: one-hot encoding.

In [59]:
# Numeric: scaled variables, no other transforms.

# Create dataframe of numerical features only
fires_feat_num = fires_feat._get_numeric_data()
fires_dt_num = fires_dt._get_numeric_data()
# Create a StandardScaler object
std_scaler = StandardScaler()
# Fit the StandardScaler object with the returns data
std_scaler.fit(fires_feat_num)
# std_scaler.mean_


StandardScaler()

In [60]:
# Transform the returns data using the fitted scaler
fires_feat_num_scaled = std_scaler.transform(fires_feat_num)
fires_feat_num_scaled = pd.DataFrame(fires_feat_num_scaled)
# Rename columns with previous column names
fires_feat_num_columns = fires_feat_num.columns
#type(fires_feat_num_columns) # pandas.core.indexes.base.Index
fires_feat_num_scaled.columns = fires_feat_num_columns
fires_feat_num_scaled.describe()

,coord_x,coord_y,ffmc,dmc,dc,isi,temp,rh,wind,rain
count,4.130000e+02,4.130000e+02,4.130000e+02,4.130000e+02,4.130000e+02,4.130000e+02,4.130000e+02,4.130000e+02,4.130000e+02,4.130000e+02
mean,-7.096825e-17,5.806493e-17,1.292482e-15,-3.204324e-16,1.032265e-16,3.010774e-17,-1.053771e-16,2.129048e-16,2.043025e-16,4.301106e-18
std,1.001213e+00,1.001213e+00,1.001213e+00,1.001213e+00,1.001213e+00,1.001213e+00,1.001213e+00,1.001213e+00,1.001213e+00,1.001213e+00
min,-1.580385e+00,-1.871175e+00,-1.269436e+01,-1.738683e+00,-2.205231e+00,-1.966848e+00,-2.906506e+00,-1.833930e+00,-1.801312e+00,-6.658494e-02
25%,-7.215705e-01,-2.527556e-01,-6.079498e-02,-6.009230e-01,-4.135485e-01,-5.452375e-01,-5.869176e-01,-7.333055e-01,-7.482331e-01,-6.658494e-02
50%,-2.921633e-01,-2.527556e-01,1.685854e-01,-5.171377e-02,4.577850e-01,-1.296898e-01,5.356571e-02,-1.829933e-01,1.232417e-02,-6.658494e-02
75%,9.960584e-01,5.564543e-01,3.979657e-01,4.849061e-01,6.595163e-01,3.514706e-01,6.767387e-01,5.507564e-01,5.388638e-01,-6.658494e-02
max,1.854873e+00,3.793294e+00,9.802390e-01,2.828094e+00,1.248912e+00,1.030274e+01,2.477016e+00,3.363463e+00,3.171562e+00,1.993311e+01


In [61]:
# Categorical: one-hot encoding.

# Create dataframe of non-numberical features only
fires_feat_categ = fires_feat.drop(columns=fires_feat._get_numeric_data().columns)

# Plotting month and day overall and when fire
#fires_dt[['area']!=0]['month'].value_counts().plot(kind = 'bar')
#fires_dt[fires_dt['area'] != 0]['month'].value_counts().plot(kind='bar')
#fires_dt['month'].value_counts().plot(kind = 'bar')
#fires_dt['day'].value_counts().plot(kind = 'bar')

# Create a OneHotEncoder object for month
onehot_m = OneHotEncoder(drop = 'first', handle_unknown='infrequent_if_exist') # handle_unknown='error' is by default
onehot_m.fit(fires_feat_categ[['month']])

OneHotEncoder(drop='first', handle_unknown='infrequent_if_exist')

In [62]:
month_enc = onehot_m.transform(fires_feat_categ[['month']])
month_enc.toarray().shape # (413, 11)

(413, 10)

In [63]:
# Create a OneHotEncoder object for day
onehot_d = OneHotEncoder(drop = 'first', handle_unknown='infrequent_if_exist') # handle_unknown='error' is by default
onehot_d.fit(fires_feat_categ[['day']])

OneHotEncoder(drop='first', handle_unknown='infrequent_if_exist')

In [64]:
day_enc = onehot_d.transform(fires_feat_categ[['day']])
day_enc.toarray().shape # (413, 6)

(413, 6)

After preprocessing of numerical features I got dataframe 

    - fires_feat_num_scaled

After preprocessing of non-numerical features I got two scipy objects: 

    - month_enc and 
    
    - day_enc

All shown above in Preproc 1 respond to Assignment requirements. Now, before moving from Preproc 1 to Preproc 2, we need to define the objects as they will get into the Pipelines.

These objects below will be presented without the above pre-processing, as same pre-processing will be done inside the Pipelines, and we don't want to do them twice.

In [65]:
# Let's set objects for next section

# X1_train_num = fires_feat_num.copy()
# #print(X1_train_num.shape)
# X1_train_cat = fires_feat_categ.copy()
# #print(X1_train_cat.shape)
# X1_train = pd.concat([X1_train_num.reset_index(drop=True),X1_train_cat.reset_index(drop=True)], axis=1)

X1_train = fires_feat.copy()
Y1_train = df_area_burnt.copy()
print(X1_train.shape, X1_train.columns)
print(Y1_train.shape, Y1_train.columns)

(413, 12) Index(['coord_x', 'coord_y', 'month', 'day', 'ffmc', 'dmc', 'dc', 'isi',
       'temp', 'rh', 'wind', 'rain'],
      dtype='object')
(413, 1) Index(['area'], dtype='object')


Let's create the transformer that will use the next section

In [66]:
# Build transformer
transformer1= ColumnTransformer(
    transformers=[
        ('numeric_transfomer', StandardScaler(), ['coord_x', 'coord_y', 'ffmc', 'dmc', 'dc', 'isi', 'temp', 'rh', 'wind', 'rain'] ),
        ('onehot', OneHotEncoder(drop = 'first', handle_unknown='infrequent_if_exist'), ['month', 'day']), 
    ], remainder='drop'
)

### Preproc 2

Create preproc1 below.

+ Numeric: scaled variables, non-linear transformation to one or more variables.
+ Categorical: one-hot encoding.

In [67]:
# Variables we will need and we do not want to use from Preproc 1, to keep it independent
# Create dataframe of numberical features only
fires_feat_num = fires_feat._get_numeric_data()
fires_dt_num = fires_dt._get_numeric_data()

Numeric: scaled variables, non-linear transformation to one or more variables.

- As per https://cwfis.cfs.nrcan.gc.ca/background/summary/fwi : 

"Canadian Forest Fire Weather Index (FWI) System consists of six components (...)"
which are FFMC, DMC, DC, ISI and two (2) others. "Calculation of the components is based on consecutive daily observations of temperature, relative humidity, wind speed, and 24-hour precipitation."

The four (4) features temp, RH, wind, rain contain information about the area burnt day only, similarly with ffmc and isi, while dmc and dc have been calculated usig wheather information from previous days.

- As per https://publications.gc.ca/collections/collection_2022/rncan-nrcan/Fo123-2-29-2021-eng.pdf :

These unitless codes represent the relative moisture content of specified layers for a standard pine forest (i.e., C-3) and have been mathematically transformed such that an increase in value represents a decrease in moisture (Van Wagner 1987)

In all these FWI indexes, higher values indicate higher fire potential

In [68]:
# Let's plot the relationships to try to obtain inputs to decide what non-linear transformation to apply

def plot_feature_pairs(data, feature_names, color_labels=None, title_prefix=''):
    """
    Helper function to create scatter plots for all possible pairs of features.
    
    Parameters:
    - data: DataFrame containing the features to be plotted.
    - feature_names: List of feature names to be used in plotting.
    - color_labels: Optional. Cluster or class labels to color the scatter plots.
    - title_prefix: Optional. Prefix for plot titles to distinguish between different sets of plots.
    """
    # Create a figure for the scatter plots
    plt.figure(figsize=(60, 60))
    
    # Counter for subplot index
    plot_number = 1
    
    # Loop through each pair of features
    for i in range(len(feature_names)):
        for j in range(i + 1, len(feature_names)):
            plt.subplot(len(feature_names)-1, len(feature_names)-1, plot_number)
            
            # Scatter plot colored by labels if provided
            if color_labels is not None:
                plt.scatter(data[feature_names[i]], data[feature_names[j]], 
                            c=color_labels, cmap='viridis', alpha=0.7)
            else:
                plt.scatter(data[feature_names[i]], data[feature_names[j]], alpha=0.7)
            
            plt.xlabel(feature_names[i])
            plt.ylabel(feature_names[j])
            plt.title(f'{title_prefix}{feature_names[i]} vs {feature_names[j]}')
            
            # Increment the plot number
            plot_number += 1

    # Adjust layout to prevent overlap
    plt.tight_layout()

    # Show the plot
    plt.show()

# Get feature names
feature_names = fires_dt.columns

# Use the helper function to plot scatter plots without coloring by cluster labels
#plot_feature_pairs(fires_dt, feature_names, title_prefix='Original Data: ')                          #________P_L_O_T________#

Observations:

- Several features show outliers o non-homogeneous distribution, like rain, FFMC and ISI, and in a different way DMC and RH, and Area.

- Rain is a very particular piece of information, that may appear to be more useful that it might be. "In the Canadian Forest Fire Weather Index (FWI) system, the "rain" component, or 24-hour precipitation, refers to the amount of rainfall recorded over the 24 hours preceding the noon observation time (usually 12:00 noon solar time) on the current day." And "In the Canadian Forest Fire Weather Index (FWI) system, the "burnt area" typically refers to the area affected by fire on a specific day, not the total area burned over the entire duration of a wildfire. If a fire lasts multiple days, the FWI system provides daily updates on fire intensity and potential spread, reflecting the conditions of each day." (Mix of actual federal government link and Google Genesis)

    If our dataset would contain actual dates, it could be possible to observe the rain impact in tomorrow outcome. For today's burnt area, there are few combinations in which the rain itself may have not been as relevant as appears, like it rained after the fire happened.
    If we open the .csv and order the dataset by rain, we observe that among the non-rain days, the area burnt =0 or =!0 is approx 50%-50%, and that for the rainy days it is 25%-75%, which is relevant. But actually, the days that rained harder, there was area burnt, while the days with soft rain there was no area burnt at all. It is relevant if it rained or not, it is not relevant how much, in this dataset. Likely, behind a rain day there were more rainy previous days than behind a non rainy day, pointing to when the terrain would have been more or less wet.

    Due to the described above, because a predictive value is observed in its category and not in its numerical value, let's convert rain from numerical to categorical.

- Now, the output variable area (burnt area) is very skewed towards zero (0.0). It could benefit from a log transformation, square root transformation or a Box-Cox transformation. Better to do it before removing outliers.

    Also, we will do a logarithmic transformation of FFMC, ISI, DMC and RH.

- And then, we'll remove some outliers. To remove some extreme outliers, we will use Interquartile Range (IQR), with outliers defined as values below Q1 - 2.5 * IQR or above Q3 + 2.5 * IQR.

In [69]:
# drop rain column from numerical dataframe
fires_dt.drop(columns='rain', inplace = True)
fires_feat_num.drop(columns='rain', inplace = True)
fires_dt_num.drop(columns='rain', inplace = True)
# generate rain column in categorical dataframe and assign values
fires_dt.insert(11, 'rained', fires_feat['rain'].apply(lambda rain: "dried" if rain == 0 else "rained"))
fires_feat_categ.loc[:, 'rained'] = fires_feat['rain'].apply(lambda rain: "dried" if rain == 0 else "rained")
# Check
print(fires_dt.shape, fires_dt.columns)
print(fires_feat_categ.shape, fires_feat_categ.columns)

(413, 13) Index(['coord_x', 'coord_y', 'month', 'day', 'ffmc', 'dmc', 'dc', 'isi',
       'temp', 'rh', 'wind', 'rained', 'area'],
      dtype='object')
(413, 3) Index(['month', 'day', 'rained'], dtype='object')


We will do a logarithmic transformation of Area.

In [70]:
# Let's apply log transformation of variable area burnt

# Applying natural logarithm transformation
# Adding a small constant to avoid log(0)
fires_dt_num.loc[:,'log_area'] = np.log(fires_dt['area'] + 0.001)  # Using +0.001 ensures no zero issues
fires_dt_num.drop(columns='area', inplace = True)
print(fires_dt_num.shape, fires_dt_num.columns)
fires_dt.loc[:,'log_area'] = np.log(fires_dt['area'] + 0.001)  # Using +0.001 ensures no zero issues
fires_dt.drop(columns='area', inplace = True)
print(fires_dt.shape, fires_dt.columns)
fires_dt_num.describe()

(413, 10) Index(['coord_x', 'coord_y', 'ffmc', 'dmc', 'dc', 'isi', 'temp', 'rh', 'wind',
       'log_area'],
      dtype='object')
(413, 13) Index(['coord_x', 'coord_y', 'month', 'day', 'ffmc', 'dmc', 'dc', 'isi',
       'temp', 'rh', 'wind', 'rained', 'log_area'],
      dtype='object')


,coord_x,coord_y,ffmc,dmc,dc,isi,temp,rh,wind,log_area
count,413.000000,413.000000,413.000000,413.000000,413.000000,413.000000,413.000000,413.000000,413.000000,413.000000
mean,4.680387,4.312349,90.644552,111.586199,552.289831,8.992978,18.990557,44.992736,3.978935,-2.368044
std,2.331616,1.237272,5.674316,63.622983,247.162399,4.577825,5.783894,16.374188,1.711346,4.478871
min,1.000000,2.000000,18.700000,1.100000,7.900000,0.000000,2.200000,15.000000,0.900000,-6.907755
25%,3.000000,4.000000,90.300000,73.400000,450.200000,6.500000,15.600000,33.000000,2.700000,-6.907755
50%,4.000000,4.000000,91.600000,108.300000,665.300000,8.400000,19.300000,42.000000,4.000000,-0.652005
75%,7.000000,5.000000,92.900000,142.400000,715.100000,10.600000,22.900000,54.000000,4.900000,1.786914
max,9.000000,9.000000,96.200000,291.300000,860.600000,56.100000,33.300000,100.000000,9.400000,6.994704


Below, we did a logarithmic transformation of FFMC, DMC, ISI, and RH. We plot it and compared plots. Did not like how the plots looked, I reverted all of them.

In [71]:
# # Let's apply log transformation of variables FFMC, ISI, DMC, RH

# # Applying natural logarithm transformation
# fires_feat_num.insert(2, 'log_ffmc', np.log(fires_dt['ffmc']))
# fires_feat_num.drop(columns='ffmc', inplace = True)
# fires_feat_num.insert(3, 'log_dmc', np.log(fires_dt['dmc']))
# fires_feat_num.drop(columns='dmc', inplace = True)
# fires_feat_num.insert(5, 'log_isi', np.log1p(fires_dt['isi'])) # Using log1p ensures no log(zero)=infinite issues
# fires_feat_num.drop(columns='isi', inplace = True)
# fires_feat_num.insert(7, 'log_rh', np.log(fires_dt['rh']))
# fires_feat_num.drop(columns='rh', inplace = True)
# print(fires_feat_num.shape, fires_feat_num.columns)
# fires_dt_num.describe()

# # Applying natural logarithm transformation
# fires_dt_num.insert(2, 'log_ffmc', np.log(fires_dt['ffmc']))
# fires_dt_num.drop(columns='ffmc', inplace = True)
# fires_dt_num.insert(3, 'log_dmc', np.log(fires_dt['dmc']))
# fires_dt_num.drop(columns='dmc', inplace = True)
# fires_dt_num.insert(5, 'log_isi', np.log1p(fires_dt['isi'])) # Using log1p ensures no log(zero)=infinite issues
# fires_dt_num.drop(columns='isi', inplace = True)
# fires_dt_num.insert(7, 'log_rh', np.log(fires_dt['rh']))
# fires_dt_num.drop(columns='rh', inplace = True)
# print(fires_dt_num.shape, fires_dt_num.columns)
# fires_dt_num.describe()

# Get feature names
feature_names = fires_dt.columns

# Use the helper function to plot scatter plots without coloring by cluster labels
#plot_feature_pairs(fires_dt, feature_names, title_prefix='Original Data: ')                         #________P_L_O_T________#

Remove outliers

In [72]:
# Now let's remove just few outliers. We need to check outliers on numeric features only but remove the rows from both numeric and categorical features

# First let's put numerical and categorical together
#fires_dt_num.columns, fires_feat_categ.columns
fires_num_cat = pd.concat([fires_dt_num, fires_feat_categ], axis=1)
fires_num_cat = fires_num_cat[['coord_x', 'coord_y', 'month', 'day', 'ffmc', 'dmc', 'dc', 'isi', 'temp', 'rh', 'wind', 'rained', 'log_area']]
print(fires_num_cat.shape, fires_num_cat.columns) # contains log_area and rained

# Compute Q1 (25th percentile) and Q3 (75th percentile) for each column
print(fires_dt_num.shape) # contains log_area
Q1 = fires_dt_num.quantile(0.25)
Q3 = fires_dt_num.quantile(0.75)
IQR = Q3 - Q1

# Define outlier thresholds
lower_bound = Q1 - 2.5 * IQR
upper_bound = Q3 + 2.5 * IQR

# Find rows where any column has an outlier
outlier_rows = ((fires_dt_num < lower_bound) | (fires_dt_num > upper_bound)).any(axis=1)

# Remove rows that contain any outlier
fires_num_cat_logarea_noutlier = fires_num_cat[~outlier_rows]
fires_logarea_noutlier = fires_num_cat_logarea_noutlier[['log_area']]
fires_num_cat_noutlier = fires_num_cat_logarea_noutlier.drop(columns='log_area')
print(fires_num_cat_noutlier.shape, fires_num_cat_noutlier.columns)
print(type(fires_logarea_noutlier))
print(fires_logarea_noutlier.shape, fires_logarea_noutlier.columns)
fires_dt_noutlier = fires_num_cat[~outlier_rows]
print(fires_dt_noutlier.shape, fires_dt_noutlier.columns)

(413, 13) Index(['coord_x', 'coord_y', 'month', 'day', 'ffmc', 'dmc', 'dc', 'isi',
       'temp', 'rh', 'wind', 'rained', 'log_area'],
      dtype='object')
(413, 10)
(389, 12) Index(['coord_x', 'coord_y', 'month', 'day', 'ffmc', 'dmc', 'dc', 'isi',
       'temp', 'rh', 'wind', 'rained'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
(389, 1) Index(['log_area'], dtype='object')
(389, 13) Index(['coord_x', 'coord_y', 'month', 'day', 'ffmc', 'dmc', 'dc', 'isi',
       'temp', 'rh', 'wind', 'rained', 'log_area'],
      dtype='object')


- I am aware that the removal of outliers above performed could be embedded in the transformer created below. I will leave it as a future improvement.

In [73]:
# Let's print it again
# Get feature names
feature_names = fires_dt_noutlier.columns

# Use the helper function to plot scatter plots without coloring by cluster labels
#plot_feature_pairs(fires_dt_noutlier, feature_names, title_prefix='Original Data: ')                  #________P_L_O_T________#

- Removing outliers, we discarded 413 - 389 = 24 rows, which is a 6% of our sample.

- The issue we were observing earlier in FFMC is not observable anymore. ISI plots improved.

- Wind measurements are not continuous, values appear every 0.5 or so. This can be noticeable in plots

- Paralel stratifications can be observed in FFMCvsISI showing that ISI was created out of FFMC (plus wind). In ISIvs wind is not that apparent.

- Paralel stratifications can be observed in DMCvsDC. It could be that every stratified line relates to a set of (x,y) with specific soil. Will not explore that.

- All plots with log_area vs numeric features show two (2) differentiated subsets: one floor of zeros (0) and one cloud of values.

- Because the last observation, we will later use a classification method first and then a regression on the cases where the classification predicted fire area burnt.

Now we need to separate numerical and categorical

In [74]:
# Create dataframe of numberical features only
fires_num_logarea_noutlier = fires_num_cat_logarea_noutlier._get_numeric_data() # contains log_area
p2_fires_feat_num_noutlier = fires_num_cat_noutlier._get_numeric_data()         # same without log_area
#print(fires_num_logarea_noutlier.columns)
print(p2_fires_feat_num_noutlier.shape, p2_fires_feat_num_noutlier.columns)

# Create dataframe of categorical features only
fires_feat_categ = fires_num_cat_noutlier.drop(columns=fires_num_cat_noutlier._get_numeric_data().columns)
print(fires_feat_categ.shape, fires_feat_categ.columns)

(389, 9) Index(['coord_x', 'coord_y', 'ffmc', 'dmc', 'dc', 'isi', 'temp', 'rh', 'wind'], dtype='object')
(389, 3) Index(['month', 'day', 'rained'], dtype='object')


Now we standardize the numerical features only (log_area excluded)

In [75]:
# Numeric: scaled variables

# Our dataframe of numberical features only, with log_area and with the outliers already removed is         p2_fires_feat_num_noutlier

# Create a StandardScaler object
std_scaler_p2 = StandardScaler()
# Fit the StandardScaler object with the returns data
std_scaler_p2.fit(p2_fires_feat_num_noutlier)
# std_scaler.mean_
# std_scaler.scale_

StandardScaler()

In [76]:
# Transform the returns data using the fitted scaler
p2_fires_feat_num_noutlier_scaled = std_scaler_p2.transform(p2_fires_feat_num_noutlier)
p2_fires_feat_num_noutlier_scaled = pd.DataFrame(p2_fires_feat_num_noutlier_scaled)
# Rename columns with previous column names
p2_fires_feat_num_noutlier_columns = p2_fires_feat_num_noutlier.columns
#type(fires_feat_num_columns) # pandas.core.indexes.base.Index
p2_fires_feat_num_noutlier_scaled.columns = p2_fires_feat_num_noutlier_columns
p2_fires_feat_num_noutlier_scaled.describe()

,coord_x,coord_y,ffmc,dmc,dc,isi,temp,rh,wind
count,3.890000e+02,3.890000e+02,3.890000e+02,3.890000e+02,3.890000e+02,3.890000e+02,3.890000e+02,3.890000e+02,3.890000e+02
mean,1.050288e-16,1.963582e-16,4.995718e-15,6.849705e-18,-5.479764e-17,2.739882e-17,-4.098407e-16,1.917917e-16,-1.141618e-16
std,1.001288e+00,1.001288e+00,1.001288e+00,1.001288e+00,1.001288e+00,1.001288e+00,1.001288e+00,1.001288e+00,1.001288e+00
min,-1.572659e+00,-1.950213e+00,-2.985161e+00,-1.780695e+00,-2.315764e+00,-1.962355e+00,-3.029777e+00,-1.867749e+00,-1.789805e+00
25%,-7.073630e-01,-2.142110e-01,-3.366639e-01,-5.197237e-01,-3.266428e-01,-5.861946e-01,-5.950205e-01,-7.293455e-01,-7.439723e-01
50%,-2.747149e-01,-2.142110e-01,9.816400e-02,-6.397033e-02,4.315990e-01,-2.008698e-01,4.947382e-02,-1.601438e-01,1.135152e-02
75%,1.023230e+00,6.537899e-01,5.725217e-01,4.384857e-01,6.434855e-01,4.321637e-01,6.760655e-01,5.355470e-01,5.342680e-01
max,1.888526e+00,1.521791e+00,1.877005e+00,2.836425e+00,1.242918e+00,3.074391e+00,2.537938e+00,3.444800e+00,3.148851e+00


In [77]:
# Let's plot again. Now it is area log transformed, outliers removed, featrues only standardized, log_area added, all plotted
p2_fires_feat_num_noutlier_scaled_plot = p2_fires_feat_num_noutlier_scaled.copy()
p2_fires_feat_num_noutlier_scaled_plot['log_area'] = fires_num_logarea_noutlier['log_area']
# Get feature names
feature_names = p2_fires_feat_num_noutlier_scaled_plot.columns

# Use the helper function to plot scatter plots without coloring by cluster labels
#plot_feature_pairs(p2_fires_feat_num_noutlier_scaled_plot, feature_names, title_prefix='Original Data: ')                    #________P_L_O_T________#

There is not a very noticeable difference before and after standardization in the plots between features. There is difference between log_area and every feature.

Now we do One-Hot Encoding to categorical values (including rained)

In [78]:
# Categorical: one-hot encoding.

# Recover dataframe of categorical features only
print(fires_feat_categ.columns, fires_feat_categ.shape)
#fires_feat_categ['month'].value_counts().plot(kind = 'bar')
#fires_feat_categ['day'].value_counts().plot(kind = 'bar')
# Create a OneHotEncoder object for month
onehot_m = OneHotEncoder(drop = 'first', handle_unknown='infrequent_if_exist') # handle_unknown='error' is by default
onehot_m.fit(fires_feat_categ[['month']])

Index(['month', 'day', 'rained'], dtype='object') (389, 3)


OneHotEncoder(drop='first', handle_unknown='infrequent_if_exist')

In [79]:
month_enc = onehot_m.transform(fires_feat_categ[['month']])
month_enc.toarray().shape # (389, 9)

(389, 9)

In [80]:
# Create a OneHotEncoder object for day
onehot_d = OneHotEncoder(drop = 'first', handle_unknown='infrequent_if_exist') # handle_unknown='error' is by default
onehot_d.fit(fires_feat_categ[['day']])

OneHotEncoder(drop='first', handle_unknown='infrequent_if_exist')

In [81]:
day_enc = onehot_d.transform(fires_feat_categ[['day']])
day_enc.toarray().shape # (389, 6)

(389, 6)

In [82]:
# Create a OneHotEncoder object for rained
onehot_r = OneHotEncoder(drop = 'first', handle_unknown='infrequent_if_exist') # handle_unknown='error' is by default
onehot_r.fit(fires_feat_categ[['rained']])

OneHotEncoder(drop='first', handle_unknown='infrequent_if_exist')

In [83]:
rained_enc = onehot_r.transform(fires_feat_categ[['rained']])
rained_enc.toarray().shape # (389, 1)

(389, 1)

After preprocessing of numerical features I got dataframe 

    - p2_fires_feat_num_noutlier_scaled

After preprocessing of non-numerical features I got two scipy objects: 

    - month_enc
    
    - day_enc

    - rained_enc

All shown above in Preproc 2 respond to Assignment requirements. Now, before moving from Preproc 2 to Model Pipelines, we need to define the objects as they will get into the Pipelines.

These objects below will be presented without the above pre-processing, as same pre-processing will be done inside the Pipelines, and we don't want to do them twice.

In [84]:
X2_train = fires_feat_train.copy()
print(X2_train.shape, X2_train.columns)
Y2_train = df_area_burnt_train.copy()
print(Y2_train.shape, Y2_train.columns)

(413, 12) Index(['coord_x', 'coord_y', 'month', 'day', 'ffmc', 'dmc', 'dc', 'isi',
       'temp', 'rh', 'wind', 'rain'],
      dtype='object')
(413, 1) Index(['area'], dtype='object')


Let's create the transformer that will use the next section

In [85]:
# Custom transformer to convert numeric to categorical (example threshold-based binning)
def numeric_to_category(X):
    series = X.iloc[:, 0] if isinstance(X, pd.DataFrame) else X.ravel()
    return np.where(series == 0, 'dried', 'rained').reshape(-1, 1)

numeric_to_category_transformer = FunctionTransformer(numeric_to_category)

# Build transformer
transformer2 = ColumnTransformer(
    transformers=[
        # Apply standard scaling to numerical features
        ('numeric', StandardScaler(), ['coord_x', 'coord_y', 'ffmc', 'dmc', 'dc', 'isi', 'temp', 'rh', 'wind']),
        
        # OneHotEncode month and day (no transformation needed)
        ('onehot_nominal', OneHotEncoder(drop='first', handle_unknown='infrequent_if_exist'), ['month', 'day']),
        
        # Convert rain and then one-hot encode
        ('rain_pipeline', Pipeline([
            ('convert_rain', numeric_to_category_transformer),
            ('onehot', OneHotEncoder(drop='first', handle_unknown='infrequent_if_exist'))
        ]), ['rain'])
    ],
    remainder='drop'
)
transformer2

ColumnTransformer(transformers=[('numeric', StandardScaler(),
                                 ['coord_x', 'coord_y', 'ffmc', 'dmc', 'dc',
                                  'isi', 'temp', 'rh', 'wind']),
                                ('onehot_nominal',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='infrequent_if_exist'),
                                 ['month', 'day']),
                                ('rain_pipeline',
                                 Pipeline(steps=[('convert_rain',
                                                  FunctionTransformer(func=<function numeric_to_category at 0x0000024CB42B9CA0>)),
                                                 ('onehot',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='infrequent_if_exist'))]),
                                 ['rain'])])

Let's summarize what we did in Preproc 2, on the training data only:
- Convert rain from numerical to categorical (named rained)
- Apply log transformation of target variable area burnt (ln + 0.001)
- Remove extreme outliers (Q1,Q3 +- 2.5 IQR) found in numerical variables (including target variable area burnt) from all features (numerical and categorical), less than 6% of the sample
- Standardize all numerical features except target variable area burnt
- One-Hot Encoding in categorical features, including rained

## Model Pipeline


Create a [model pipeline](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html): 

+ Add a step labelled `preprocessing` and assign the Column Transformer from the previous section.
+ Add a step labelled `regressor` and assign a regression model to it. 

## Regressor

+ Use a regression model to perform a prediction. 

    - Choose a baseline regressor, tune it (if necessary) using grid search, and evaluate it using cross-validation.
    - Choose a more advance regressor, tune it (if necessary) using grid search, and evaluate it using cross-validation.
    - Both model choices are up to you, feel free to experiment.

In [86]:
# Pipeline A = preproc1 + baseline
pipe_A = Pipeline(
    [
        ('preprocessing', transformer1), 
        ('poly', PolynomialFeatures()),
        ('model', LinearRegression())
    ]
)
pipe_A

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('numeric_transfomer',
                                                  StandardScaler(),
                                                  ['coord_x', 'coord_y', 'ffmc',
                                                   'dmc', 'dc', 'isi', 'temp',
                                                   'rh', 'wind', 'rain']),
                                                 ('onehot',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='infrequent_if_exist'),
                                                  ['month', 'day'])])),
                ('poly', PolynomialFeatures()), ('model', LinearRegression())])

In [87]:
# Pipeline B = preproc1 + baseline

pipe_B_pre = Pipeline(
    [
        ('preprocessing', transformer2), 
        ('poly', PolynomialFeatures()),
        ('model', LinearRegression())  
    ]
)

pipe_B =  TransformedTargetRegressor(regressor=pipe_B_pre, func=np.log1p, inverse_func=np.expm1)   # Apply log transform to target

In [88]:
# Pipeline C = preproc1 + advanced model


In [89]:
# Pipeline D = preproc2 + advanced model

    

# Tune Hyperparams

+ Perform GridSearch on each of the four pipelines. 
+ Tune at least one hyperparameter per pipeline.
+ Experiment with at least four value combinations per pipeline.

Pipeline A

In [90]:
param_grid = {
    'poly__degree': [1, 2, 3, 4],
    'poly__interaction_only': [False, True],
    'poly__include_bias': [False],
    'model__fit_intercept': [True, False]
}
cv_strategy = KFold(n_splits=5, shuffle=True, random_state=42)
scoring = {
    'neg_rmse': 'neg_root_mean_squared_error',
    'r2': 'r2'
}
grid_search = GridSearchCV(pipe_A, param_grid, scoring=scoring, refit='neg_rmse', cv=cv_strategy, return_train_score = True) 
grid_search.fit(X1_train, Y1_train)

print("Best parameters:", grid_search.best_params_)
# refit='neg_mse'  # Best parameters: {'model__fit_intercept': True, 'poly__degree': 1, 'poly__include_bias': False, 'poly__interaction_only': False}

c:\miniconda3\envs\dsi_participant\lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
c:\miniconda3\envs\dsi_participant\lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
c:\miniconda3\envs\dsi_participant\lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
c:\miniconda3\envs\dsi_participant\lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
c:\miniconda3\envs\dsi_participant\lib\site-packages\sklearn

Best parameters: {'model__fit_intercept': True, 'poly__degree': 1, 'poly__include_bias': False, 'poly__interaction_only': False}


In [91]:
# Get the best pipeline from GridSearchCV, which is the fit to the whole trainiing set with the best grid parameters
best_pipeline = grid_search.best_estimator_

# Access the regression step and grab coefficients
coefficients = best_pipeline.named_steps['model'].coef_
intercept = best_pipeline.named_steps['model'].intercept_

print("Coefficients:", coefficients)
print("Number of coefficients:", len(coefficients[0])) # Number of coefficients: 26
print("Intercept:", intercept) # Intercept: [-68.03289611]

Coefficients: [[  5.50533611   2.42594296  -1.29652244  14.2526514  -43.80052654
   -2.36563636   8.18461269  -3.06340597   3.13064156  -0.7112512
   79.16092897  67.20689227  10.88556079  21.40994988  44.57401277
   23.8069739    4.22793205  22.06813443 101.72778261 112.72509654
   -0.95109802  18.15719001   3.70999875  10.43905947   3.00586587
    2.49154527]]
Number of coefficients: 26
Intercept: [-68.03289611]


In [92]:
# Get the transformed feature names from the preprocessing step
preprocessor = best_pipeline.named_steps['preprocessing']
preprocessed_feature_names = preprocessor.get_feature_names_out()

# Now get polynomial feature names based on these
poly = best_pipeline.named_steps['poly']
feature_names = poly.get_feature_names_out(input_features=preprocessed_feature_names)

# Combine with coefficients
coefs = best_pipeline.named_steps['model'].coef_.ravel() # .ravel() flattens from (1,27) or (27,1) to (27,)
coef_df = pd.DataFrame({'Feature': feature_names, 'Coefficient': coefs})

print(coef_df)

                        Feature  Coefficient
0   numeric_transfomer__coord_x     5.505336
1   numeric_transfomer__coord_y     2.425943
2      numeric_transfomer__ffmc    -1.296522
3       numeric_transfomer__dmc    14.252651
4        numeric_transfomer__dc   -43.800527
5       numeric_transfomer__isi    -2.365636
6      numeric_transfomer__temp     8.184613
7        numeric_transfomer__rh    -3.063406
8      numeric_transfomer__wind     3.130642
9      numeric_transfomer__rain    -0.711251
10            onehot__month_aug    79.160929
11            onehot__month_dec    67.206892
12            onehot__month_feb    10.885561
13            onehot__month_jan    21.409950
14            onehot__month_jul    44.574013
15            onehot__month_jun    23.806974
16            onehot__month_mar     4.227932
17            onehot__month_may    22.068134
18            onehot__month_oct   101.727783
19            onehot__month_sep   112.725097
20              onehot__day_mon    -0.951098
21        

In [93]:
# Get the cross-validation results as a DataFrame
cv_results = grid_search.cv_results_

# Extract the mean negative MSE and r2 scores
neg_rmse_scores = cv_results['mean_test_neg_rmse']

# Convert to RMSE
rmse_scores = (-neg_rmse_scores)

# And if you're curious about the best RMSE, which is the average RMSE of the folds:
best_rmse = -grid_search.best_score_  # grid_search.best_score_ is already neg_root_mean_squared_error, we don't need to do sqrt

# View all RMSE scores across the grid
for params, score in zip(cv_results['params'], rmse_scores):
    print(f"Params: {params} → RMSE: {score:.2f}")
print()  
print("Best RMSE from CV:", best_rmse)          # Best RMSE from CV: 59.38389577288659
print()
print((cv_results.keys()))

Params: {'model__fit_intercept': True, 'poly__degree': 1, 'poly__include_bias': False, 'poly__interaction_only': False} → RMSE: 59.38
Params: {'model__fit_intercept': True, 'poly__degree': 1, 'poly__include_bias': False, 'poly__interaction_only': True} → RMSE: 59.38
Params: {'model__fit_intercept': True, 'poly__degree': 2, 'poly__include_bias': False, 'poly__interaction_only': False} → RMSE: 1503.26
Params: {'model__fit_intercept': True, 'poly__degree': 2, 'poly__include_bias': False, 'poly__interaction_only': True} → RMSE: 209.25
Params: {'model__fit_intercept': True, 'poly__degree': 3, 'poly__include_bias': False, 'poly__interaction_only': False} → RMSE: 1080.58
Params: {'model__fit_intercept': True, 'poly__degree': 3, 'poly__include_bias': False, 'poly__interaction_only': True} → RMSE: 479.13
Params: {'model__fit_intercept': True, 'poly__degree': 4, 'poly__include_bias': False, 'poly__interaction_only': False} → RMSE: 28818.35
Params: {'model__fit_intercept': True, 'poly__degree': 4

In [94]:
r2_scores = cv_results['mean_test_r2']
for params, score in zip(cv_results['params'], r2_scores):
    print(f"Params: {params} → R²: {score:.2f}")
print()  

# Get the cross-validation results
cv_results = grid_search.cv_results_

# Extract the mean test R² scores
r2_scores = cv_results['mean_test_r2']

# Find the best RMSE model index
best_index = grid_search.best_index_  # Index of best model (based on neg_rmse)

# Get the corresponding R² score for that best model
best_r2 = r2_scores[best_index]

print("Best R² from CV:", best_r2)  # Best R² from CV: -0.7016411827474011

Params: {'model__fit_intercept': True, 'poly__degree': 1, 'poly__include_bias': False, 'poly__interaction_only': False} → R²: -0.70
Params: {'model__fit_intercept': True, 'poly__degree': 1, 'poly__include_bias': False, 'poly__interaction_only': True} → R²: -0.70
Params: {'model__fit_intercept': True, 'poly__degree': 2, 'poly__include_bias': False, 'poly__interaction_only': False} → R²: -18376.61
Params: {'model__fit_intercept': True, 'poly__degree': 2, 'poly__include_bias': False, 'poly__interaction_only': True} → R²: -97.86
Params: {'model__fit_intercept': True, 'poly__degree': 3, 'poly__include_bias': False, 'poly__interaction_only': False} → R²: -3672.36
Params: {'model__fit_intercept': True, 'poly__degree': 3, 'poly__include_bias': False, 'poly__interaction_only': True} → R²: -313.57
Params: {'model__fit_intercept': True, 'poly__degree': 4, 'poly__include_bias': False, 'poly__interaction_only': False} → R²: -8703921.38
Params: {'model__fit_intercept': True, 'poly__degree': 4, 'poly

In [95]:
#After Cross Validation process inside GridSearch and after assessing at the errors, if the polynomial coeff is 1, then we fit a standard LinearRegression to the whole Trainig set without folding subsets, and take those coeff.
# Get the negative rrot mean squared error and R2 obtained after retrained on the entire Training dataset

# Make predictions on the full training data
train_preds_1 = best_pipeline.predict(X1_train)

# Compute RMSE root mean squared error
train_rmse_1 = root_mean_squared_error(Y1_train, train_preds_1)

print("RMSE on full training data:", train_rmse_1)  # RMSE in original target units     # RMSE on full training data: 66.48140554239002

# Compute R² on the full training set
train_r2_1 = r2_score(Y1_train, train_preds_1)

print("R² score on full training data:", train_r2_1)        # R² score on full training data: 0.05571835082538645

RMSE on full training data: 66.48140554239002
R² score on full training data: 0.05571835082538645


In [96]:
# Get the negative root mean squared error RMSE and R2 on the TEST dataset
# Recover TEST dataset
X1_test = fires_feat_test.copy()
Y1_test = df_area_burnt_test.copy()

# Get the best estimator from GridSearchCV
best_model = grid_search.best_estimator_

# Predict on the training or test set
Y1_pred = best_model.predict(X1_test)

# Calculate RMSE
rmse = root_mean_squared_error(Y1_test, Y1_pred)

# Calculate R-squared
r2 = r2_score(Y1_test, Y1_pred)

print("RMSE:", rmse)    # RMSE: 42.07356539407348
print("R²:", r2)        # R²: -0.16687246410040668

RMSE: 42.07356539407348
R²: -0.16687246410040668


c:\miniconda3\envs\dsi_participant\lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(


Pipeline B

In [97]:
param_grid = {
    'regressor__poly__degree': [1, 2, 3, 4],
    'regressor__poly__interaction_only': [False, True],
    'regressor__poly__include_bias': [False],
    'regressor__model__fit_intercept': [True, False]
}
cv_strategy = KFold(n_splits=5, shuffle=True, random_state=42)
scoring = {
    'neg_rmse': 'neg_root_mean_squared_error',
    'r2': 'r2'
}
grid_search_B = GridSearchCV(pipe_B, param_grid, scoring=scoring, refit='neg_rmse', cv=cv_strategy, return_train_score = True) 
grid_search_B.fit(X2_train, Y2_train)

print("Best parameters:", grid_search_B.best_params_) 
# scoring='neg_mean_squared_error'; Best parameters: {'model__fit_intercept': False, 'poly__degree': 1, 'poly__include_bias': False, 'poly__interaction_only': False}

c:\miniconda3\envs\dsi_participant\lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
c:\miniconda3\envs\dsi_participant\lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
c:\miniconda3\envs\dsi_participant\lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
c:\miniconda3\envs\dsi_participant\lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
c:\miniconda3\envs\dsi_participant\lib\site-packages\sklearn

Best parameters: {'regressor__model__fit_intercept': True, 'regressor__poly__degree': 1, 'regressor__poly__include_bias': False, 'regressor__poly__interaction_only': False}


In [98]:
# Get the best pipeline from GridSearchCV, which is the fit to the whole trainiing set with the best grid parameters
best_pipeline_B = grid_search_B.best_estimator_

# Now access the inner pipeline (pipe_B_pre)
inner_pipeline = best_pipeline_B.regressor_

# Then access the model step inside that inner pipeline
model = inner_pipeline.named_steps['model']

# Access the regression step and grab coefficients
coefficients = model.coef_
intercept = model.intercept_

print("Coefficients:", coefficients)
print("Number of coefficients:", len(coefficients)) # Number of coefficients: 26
print("Intercept:", intercept) # Intercept: -0.36817542069750475

Coefficients: [ 0.08816938  0.02563217  0.048618    0.30127116 -0.69858038 -0.09966256
  0.25145816  0.04342262  0.05792158  1.29662805  2.91228996  0.74906412
  0.23166078  0.88436505  0.57170377  0.2885414   1.27206387  1.52466895
  2.09930911 -0.06992746  0.16058523  0.11106155 -0.24164297  0.25162799
  0.18963544 -0.90099778]
Number of coefficients: 26
Intercept: -0.36817542069750475


In [99]:
# Get the cross-validation results as a DataFrame
cv_results_B = grid_search_B.cv_results_

# Extract the mean negative MSE and r2 scores
neg_rmse_scores = cv_results_B['mean_test_neg_rmse']

# Convert to RMSE
rmse_scores = (-neg_rmse_scores)

# And if you're curious about the best RMSE, which is the average RMSE of the folds:
best_rmse = -grid_search_B.best_score_  # grid_search.best_score_ is already neg_root_mean_squared_error, we don't need to do sqrt

# View all RMSE scores across the grid
for params, score in zip(cv_results_B['params'], rmse_scores):
    print(f"Params: {params} → RMSE: {score:.2f}")
print() 
print("Best RMSE from CV:", best_rmse)          # Best RMSE from CV: 55.43786584769059
print()
print((cv_results_B.keys()))

Params: {'regressor__model__fit_intercept': True, 'regressor__poly__degree': 1, 'regressor__poly__include_bias': False, 'regressor__poly__interaction_only': False} → RMSE: 55.44
Params: {'regressor__model__fit_intercept': True, 'regressor__poly__degree': 1, 'regressor__poly__include_bias': False, 'regressor__poly__interaction_only': True} → RMSE: 55.44
Params: {'regressor__model__fit_intercept': True, 'regressor__poly__degree': 2, 'regressor__poly__include_bias': False, 'regressor__poly__interaction_only': False} → RMSE: 98135968770.94
Params: {'regressor__model__fit_intercept': True, 'regressor__poly__degree': 2, 'regressor__poly__include_bias': False, 'regressor__poly__interaction_only': True} → RMSE: 1128438.16
Params: {'regressor__model__fit_intercept': True, 'regressor__poly__degree': 3, 'regressor__poly__include_bias': False, 'regressor__poly__interaction_only': False} → RMSE: 34499109697950980348780555956079431121899566041746679821444466266341376.00
Params: {'regressor__model__f

In [100]:
r2_scores = cv_results_B['mean_test_r2']
for params, score in zip(cv_results_B['params'], r2_scores):
    print(f"Params: {params} → R²: {score:.2f}")
print()

# Get the cross-validation results
cv_results_B = grid_search_B.cv_results_

# Extract the mean test R² scores
r2_scores = cv_results_B['mean_test_r2']

# Find the best RMSE model index
best_index = grid_search_B.best_index_  # Index of best model (based on neg_rmse)

# Get the corresponding R² score for that best model
best_r2 = r2_scores[best_index]

print("Best R² from CV:", best_r2)   # Best R² from CV: -0.05412144361174618

Params: {'regressor__model__fit_intercept': True, 'regressor__poly__degree': 1, 'regressor__poly__include_bias': False, 'regressor__poly__interaction_only': False} → R²: -0.05
Params: {'regressor__model__fit_intercept': True, 'regressor__poly__degree': 1, 'regressor__poly__include_bias': False, 'regressor__poly__interaction_only': True} → R²: -0.05
Params: {'regressor__model__fit_intercept': True, 'regressor__poly__degree': 2, 'regressor__poly__include_bias': False, 'regressor__poly__interaction_only': False} → R²: -6211404906123319296.00
Params: {'regressor__model__fit_intercept': True, 'regressor__poly__degree': 2, 'regressor__poly__include_bias': False, 'regressor__poly__interaction_only': True} → R²: -826241080.82
Params: {'regressor__model__fit_intercept': True, 'regressor__poly__degree': 3, 'regressor__poly__include_bias': False, 'regressor__poly__interaction_only': False} → R²: -41800705830771445628039033681071066574465928030805165445392631296381761864733859873855389593828303650

In [101]:
#After Cross Validation process inside GridSearch and after assessing at the errors, if the polynomial coeff is 1, then we fit a standard LinearRegression to the whole Trainig set without folding subsets, and take those coeff.
# Get the negative mean squared error and R2 obtained after retrained on the entire Training dataset

# Make predictions on the full training data
train_preds_2 = best_pipeline_B.predict(X2_train)

# Compute RMSE root mean squared error
train_rmse_2 = root_mean_squared_error(Y2_train, train_preds_2)

print("RMSE on full training data:", train_rmse_2)  # RMSE in original target units     # RMSE on full training data: 68.98405061371875

# Compute R² on the full training set
train_r2_2 = r2_score(Y2_train, train_preds_2)

print("R² score on full training data:", train_r2_2)                # R² score on full training data: -0.016713401138988893

RMSE on full training data: 68.98405061371875
R² score on full training data: -0.016713401138988893


In [102]:
# RMSE and R2 of BestPipeline on Test dataset
# Recover Test dataset
X2_test = fires_feat_test.copy()
Y2_test = df_area_burnt_test.copy()

# Predict on the training or test set
Y2_test_pred = best_pipeline_B.predict(X2_test)  # or X1_train, depending on your evaluation

# Calculate RMSE
rmse = root_mean_squared_error(Y2_test, Y2_test_pred)       # RMSE: 40.40514419727944

# Calculate R-squared
r2 = r2_score(Y2_test, Y2_test_pred)                        # R²: -0.07616305980639515

print("RMSE:", rmse)
print("R²:", r2)

RMSE: 40.40514419727944
R²: -0.07616305980639515


c:\miniconda3\envs\dsi_participant\lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(


Pipeline C

Pipeline D

# Evaluate

+ Which model has the best performance?

# Export

+ Save the best performing model to a pickle file.

# Explain

+ Use SHAP values to explain the following only for the best-performing model:

    - Select an observation in your test set and explain which are the most important features that explain that observation's specific prediction.

    - In general, across the complete training set, which features are the most and least important.

+ If you were to remove features from the model, which ones would you remove? Why? How would you test that these features are actually enhancing model performance?

*(Answer here.)*

## Criteria

The [rubric](./assignment_2_rubric_clean.xlsx) contains the criteria for assessment.

## Submission Information

🚨 **Please review our [Assignment Submission Guide](https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md)** 🚨 for detailed instructions on how to format, branch, and submit your work. Following these guidelines is crucial for your submissions to be evaluated correctly.

### Submission Parameters:
* Submission Due Date: `HH:MM AM/PM - DD/MM/YYYY`
* The branch name for your repo should be: `assignment-2`
* What to submit for this assignment:
    * This Jupyter Notebook (assignment_2.ipynb) should be populated and should be the only change in your pull request.
* What the pull request link should look like for this assignment: `https://github.com/<your_github_username>/production/pull/<pr_id>`
    * Open a private window in your browser. Copy and paste the link to your pull request into the address bar. Make sure you can see your pull request properly. This helps the technical facilitator and learning support staff review your submission easily.

Checklist:
- [ ] Created a branch with the correct naming convention.
- [ ] Ensured that the repository is public.
- [ ] Reviewed the PR description guidelines and adhered to them.
- [ ] Verify that the link is accessible in a private browser window.

If you encounter any difficulties or have questions, please don't hesitate to reach out to our team via our Slack at the `help` channel. Our Technical Facilitators and Learning Support staff are here to help you navigate any challenges.

# Reference

Cortez,Paulo and Morais,Anbal. (2008). Forest Fires. UCI Machine Learning Repository. https://doi.org/10.24432/C5D88D.